name: Build macOS binaries of Helium
on:
  workflow_dispatch:
    inputs:
      runner:
        required: false
        description: "Runner image name"
        default: "macos-latest"
      do-release:
        required: false
        type: boolean
        description: "Create a release after build is done"
        default: false

permissions:
  contents: write

jobs:
  build:
    name: Build macOS binaries of Helium
    uses: ./.github/workflows/building.yml
    secrets: inherit
    with:
      arch: arm64
      os: ${{ inputs.runner }}
